# Defines the customer's target environment where memcached-operator should be deployed
apiVersion: porter.sh/v1
kind: CredentialSet
metadata:
  name: mycustomer-cluster
  namespace: mycustomer
spec:
  schemaVersion: 1.0.1
  namespace: mycustomer
  name: mycustomer-cluster
  credentials:
    - name: kubeconfig
      source:
        secret: kubeconfig
